[package]
name = "bili-fm"
version = "2.0.33-preview"
description = "bili-FM - 用音频聆听 B 站内容"
authors = ["vst"]
edition = "2021"

[lib]
name = "bili_fm_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[profile.release.package."*"]
opt-level = "s"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-shell = "2"
tauri-plugin-store = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls", "stream"], default-features = false }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time", "sync"] }
md5 = "0.7"
flate2 = "1"
html-escape = "0.2"
image = "0.25"
axum = "0.8"
hmac = "0.12"
sha2 = "0.10"
roxmltree = "0.20"
dirs = "6"
percent-encoding = "2"
chrono = "0.4"
