// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CoinVideo(arg1:string,arg2:number):Promise<boolean>;

export function Follow(arg1:number):Promise<boolean>;

export function GetBLFavFolderList():Promise<Array<any>>;

export function GetBLFavFolderListDetail(arg1:number,arg2:number):Promise<Array<any>>;

export function GetBLFeedList(arg1:string):Promise<service.FeedList>;

export function GetBLHistoryList(arg1:number,arg2:number,arg3:string,arg4:number):Promise<service.HistoryList>;

export function GetBLRCMDList(arg1:number):Promise<service.RCMDList>;

export function GetBLUserInfo():Promise<service.UserInfo>;

export function GetBiliTicket(arg1:string):Promise<string>;

export function GetCList(arg1:string):Promise<service.VideoInfo>;

export function GetImageProxyPort():Promise<number>;

export function GetLoginQRCode():Promise<string>;

export function GetLoginQRCodeStatus():Promise<boolean>;

export function GetLoginStatus():Promise<boolean>;

export function GetSESSDATA():Promise<string>;

export function GetSeriesList(arg1:number):Promise<Array<any>>;

export function GetSeriesVideos(arg1:number,arg2:number,arg3:number):Promise<Array<service.SeriesVideosResponse_Archive>>;

export function GetUpVideoList(arg1:number,arg2:string):Promise<service.FeedList>;

export function GetUrlByCid(arg1:number,arg2:number):Promise<service.PlayURLInfo>;

export function HasCoin(arg1:string):Promise<number>;

export function HasLiked(arg1:string):Promise<boolean>;

export function HmacSha256(arg1:string,arg2:string):Promise<string>;

export function IsFollowing(arg1:number):Promise<boolean>;

export function LikeVideo(arg1:string,arg2:number):Promise<boolean>;

export function ProxyImage(arg1:string):Promise<string>;

export function ReportPlayProgress(arg1:number,arg2:number,arg3:number):Promise<boolean>;

export function SearchVideo(arg1:string,arg2:string):Promise<Array<service.SearchResult>>;

export function SetLoginStatus(arg1:boolean):Promise<void>;

export function SetSESSDATA(arg1:string):Promise<void>;

export function Unfollow(arg1:number):Promise<boolean>;
