// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CoinVideo(arg1, arg2) {
  return window['go']['service']['BL']['CoinVideo'](arg1, arg2);
}

export function Follow(arg1) {
  return window['go']['service']['BL']['Follow'](arg1);
}

export function GetAppVersion() {
  return window['go']['service']['BL']['GetAppVersion']();
}

export function GetBLFavFolderList() {
  return window['go']['service']['BL']['GetBLFavFolderList']();
}

export function GetBLFavFolderListDetail(arg1, arg2) {
  return window['go']['service']['BL']['GetBLFavFolderListDetail'](arg1, arg2);
}

export function GetBLFeedList(arg1) {
  return window['go']['service']['BL']['GetBLFeedList'](arg1);
}

export function GetBLHistoryList(arg1, arg2, arg3, arg4) {
  return window['go']['service']['BL']['GetBLHistoryList'](arg1, arg2, arg3, arg4);
}

export function GetBLPopularList(arg1) {
  return window['go']['service']['BL']['GetBLPopularList'](arg1);
}

export function GetBLRCMDList(arg1) {
  return window['go']['service']['BL']['GetBLRCMDList'](arg1);
}

export function GetBLUserInfo() {
  return window['go']['service']['BL']['GetBLUserInfo']();
}

export function GetBiliTicket(arg1) {
  return window['go']['service']['BL']['GetBiliTicket'](arg1);
}

export function GetCList(arg1) {
  return window['go']['service']['BL']['GetCList'](arg1);
}

export function GetDanmakuList(arg1) {
  return window['go']['service']['BL']['GetDanmakuList'](arg1);
}

export function GetImageProxyPort() {
  return window['go']['service']['BL']['GetImageProxyPort']();
}

export function GetLoginQRCode() {
  return window['go']['service']['BL']['GetLoginQRCode']();
}

export function GetLoginQRCodeStatus() {
  return window['go']['service']['BL']['GetLoginQRCodeStatus']();
}

export function GetLoginStatus() {
  return window['go']['service']['BL']['GetLoginStatus']();
}

export function GetSESSDATA() {
  return window['go']['service']['BL']['GetSESSDATA']();
}

export function GetSeriesList(arg1) {
  return window['go']['service']['BL']['GetSeriesList'](arg1);
}

export function GetSeriesVideos(arg1, arg2, arg3) {
  return window['go']['service']['BL']['GetSeriesVideos'](arg1, arg2, arg3);
}

export function GetUpVideoList(arg1, arg2) {
  return window['go']['service']['BL']['GetUpVideoList'](arg1, arg2);
}

export function GetUrlByCid(arg1, arg2) {
  return window['go']['service']['BL']['GetUrlByCid'](arg1, arg2);
}

export function HasCoin(arg1) {
  return window['go']['service']['BL']['HasCoin'](arg1);
}

export function HasLiked(arg1) {
  return window['go']['service']['BL']['HasLiked'](arg1);
}

export function HmacSha256(arg1, arg2) {
  return window['go']['service']['BL']['HmacSha256'](arg1, arg2);
}

export function IsFollowing(arg1) {
  return window['go']['service']['BL']['IsFollowing'](arg1);
}

export function LikeVideo(arg1, arg2) {
  return window['go']['service']['BL']['LikeVideo'](arg1, arg2);
}

export function ProxyImage(arg1) {
  return window['go']['service']['BL']['ProxyImage'](arg1);
}

export function ReportPlayProgress(arg1, arg2, arg3) {
  return window['go']['service']['BL']['ReportPlayProgress'](arg1, arg2, arg3);
}

export function SearchVideo(arg1, arg2) {
  return window['go']['service']['BL']['SearchVideo'](arg1, arg2);
}

export function SetLoginStatus(arg1) {
  return window['go']['service']['BL']['SetLoginStatus'](arg1);
}

export function SetSESSDATA(arg1) {
  return window['go']['service']['BL']['SetSESSDATA'](arg1);
}

export function Unfollow(arg1) {
  return window['go']['service']['BL']['Unfollow'](arg1);
}
