// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CoinVideo(arg1, arg2) {
  return window['go']['main']['BL']['CoinVideo'](arg1, arg2);
}

export function GetBLFavFolderList() {
  return window['go']['main']['BL']['GetBLFavFolderList']();
}

export function GetBLFavFolderListDetail(arg1, arg2) {
  return window['go']['main']['BL']['GetBLFavFolderListDetail'](arg1, arg2);
}

export function GetBLFeedList(arg1) {
  return window['go']['main']['BL']['GetBLFeedList'](arg1);
}

export function GetBLRCMDList(arg1) {
  return window['go']['main']['BL']['GetBLRCMDList'](arg1);
}

export function GetBLUserInfo() {
  return window['go']['main']['BL']['GetBLUserInfo']();
}

export function GetBiliTicket(arg1) {
  return window['go']['main']['BL']['GetBiliTicket'](arg1);
}

export function GetCList(arg1) {
  return window['go']['main']['BL']['GetCList'](arg1);
}

export function GetLoginQRCode() {
  return window['go']['main']['BL']['GetLoginQRCode']();
}

export function GetLoginQRCodeStatus() {
  return window['go']['main']['BL']['GetLoginQRCodeStatus']();
}

export function GetLoginStatus() {
  return window['go']['main']['BL']['GetLoginStatus']();
}

export function GetSESSDATA() {
  return window['go']['main']['BL']['GetSESSDATA']();
}

export function GetUrlByCid(arg1, arg2) {
  return window['go']['main']['BL']['GetUrlByCid'](arg1, arg2);
}

export function HasCoin(arg1) {
  return window['go']['main']['BL']['HasCoin'](arg1);
}

export function HasLiked(arg1) {
  return window['go']['main']['BL']['HasLiked'](arg1);
}

export function HmacSha256(arg1, arg2) {
  return window['go']['main']['BL']['HmacSha256'](arg1, arg2);
}

export function LikeVideo(arg1, arg2) {
  return window['go']['main']['BL']['LikeVideo'](arg1, arg2);
}

export function SearchVideo(arg1, arg2) {
  return window['go']['main']['BL']['SearchVideo'](arg1, arg2);
}

export function SetLoginStatus(arg1) {
  return window['go']['main']['BL']['SetLoginStatus'](arg1);
}

export function SetSESSDATA(arg1) {
  return window['go']['main']['BL']['SetSESSDATA'](arg1);
}
