// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBiliTicket(arg1) {
  return window['go']['main']['BL']['GetBiliTicket'](arg1);
}

export function GetLoginQRCode() {
  return window['go']['main']['BL']['GetLoginQRCode']();
}

export function GetLoginStatus() {
  return window['go']['main']['BL']['GetLoginStatus']();
}

export function GetSESSDATA() {
  return window['go']['main']['BL']['GetSESSDATA']();
}

export function HmacSha256(arg1, arg2) {
  return window['go']['main']['BL']['HmacSha256'](arg1, arg2);
}

export function SearchVideo(arg1, arg2) {
  return window['go']['main']['BL']['SearchVideo'](arg1, arg2);
}

export function SetLoginStatus(arg1) {
  return window['go']['main']['BL']['SetLoginStatus'](arg1);
}

export function SetSESSDATA(arg1) {
  return window['go']['main']['BL']['SetSESSDATA'](arg1);
}
