// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CheckForUpdates(arg1:context.Context,arg2:boolean):Promise<void>;

export function GetPlatform():Promise<string>;

export function ShowAbout(arg1:context.Context):Promise<void>;

export function ShowVersion(arg1:context.Context):Promise<void>;
