// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1) {
  return window['go']['main']['Menu']['CheckForUpdates'](arg1);
}

export function GetPlatform() {
  return window['go']['main']['Menu']['GetPlatform']();
}

export function SetAppContext(arg1) {
  return window['go']['main']['Menu']['SetAppContext'](arg1);
}

export function ShowAbout() {
  return window['go']['main']['Menu']['ShowAbout']();
}

export function ShowVersion() {
  return window['go']['main']['Menu']['ShowVersion']();
}
