// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export interface UpdateResult {
  hasUpdate: boolean;
  latestVersion: string;
  downloadUrl: string;
  isLatest: boolean;
  error: string;
}

export function CheckForUpdates(arg1:boolean,arg2:string):Promise<UpdateResult>;

export function CloseApp():Promise<void>;

export function GetPlatform():Promise<string>;

export function SetAppContext(arg1:context.Context):Promise<void>;
