// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function ApplyUpdate(arg1:string):Promise<main.ApplyResult>;

export function CheckForUpdates(arg1:boolean,arg2:string):Promise<main.UpdateResult>;

export function CloseApp():Promise<void>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function GetPlatform():Promise<string>;

export function IsMSStoreInstall():Promise<boolean>;

export function SetAppContext(arg1:context.Context):Promise<void>;
